### ISSUE TITLE
İp Camera

### ISSUE THREAD

**Issue by CodrTks** [takuya-takeuchi/UltraFaceDotNet#14]
all of your samples detect faces from the picture taken from the file. Is it possible to detect a face from the 1080p image from the ip camera?

**Comment by takuya-takeuchi** [comment]
@CodrTks 
You can do what you want to do.
You can use Aforge.NET, OpenCVSharp and other libraries support ip camera.

**Comment by CodrTks** [comment]
> @CodrTks
> Yapmak istediğinizi yapabilirsiniz.
> Aforge.NET, OpenCVSharp ve ip kamerayı destekleyen diğer kütüphaneleri kullanabilirsiniz.

**Comment by CodrTks** [comment]
Thank you for your interest. I already get the camera image as a bitmap via A-Forge stream. But can you give an example of what to do to use bitmap instead of file path. Thank you again for your time

**Comment by takuya-takeuchi** [comment]
FromPixels accept IntPtr and IntPtr indicates image pixel data.
So you can pass BitmapData.Scan0 if image width is multiple of 4.
If not 4, you can create byte array, load BitmapData.Scan0 to array and cast to IntPtr.

It could help you.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/e91da42cabb351bc841b2ceead5270fe11225a8a/src/FaceRecognitionDotNet/FaceRecognition.cs#L545

**Comment by CodrTks** [comment]
I did it like this but could not complete it. I want to detect the face image and show it in another picture box.

`  using (var unknownImage = FaceRecognition.LoadImage(bitm))
            {
                var faceLocations = _FaceRecognition.FaceLocations(unknownImage, 0, model).ToArray();
                using (Graphics g = Graphics.FromImage(bitm))
                {
                    foreach (var faceLocation in faceLocations)
                    {

                        var top = faceLocation.Top;
                        var right = faceLocation.Right;
                        var bottom = faceLocation.Bottom;
                        var left = faceLocation.Left;
                        Rectangle rct = new Rectangle(left, top, right, Bottom);
                        g.DrawRectangle(new Pen(Color.Yellow) { Width = 2 }, rct);
                    }
                    pictureBox1.Image = bitm;
                    g.Dispose();
                }
                
            }

**Comment by CodrTks** [comment]
sorry to keep you busy but i need help Can you help me finish the structure below

``var param = new UltraFaceParameter
            {
                InputWidth = 320,
                InputLength = 240,
                NumThread = 1,
                ScoreThreshold = 0.7f
            };
            var ultraFace = UltraFaceDotNet.UltraFace.Create(param);
            var bytesFaces1 = ConvertImageToBinary(btm);
            var mat1 = Cv2.ImDecode(bytesFaces1, OpenCvSharp.ImreadModes.Color);
            var bytes1 = new byte[mat1.Rows * mat1.Cols * mat1.ElemSize()];
            Marshal.Copy(mat1.Data, bytes1, 0, bytes1.Length);
            var inMat = NcnnDotNet.Mat.FromPixels(mat1.Data, NcnnDotNet.PixelType.Bgr2Rgb, mat1.Cols, mat1.Rows);
            var faceInfos = ultraFace.Detect(inMat).ToArray();
            for (var j = 0; j < faceInfos.Length; j++)
            {
                var face = faceInfos[j];
                var pt1 = new NcnnDotNet.OpenCV.Point<float>(face.X1, face.Y1);
                var pt2 = new NcnnDotNet.OpenCV.Point<float>(face.X2, face.Y2);
                ????
            }

>

**Comment by CodrTks** [comment]
I managed to capture faces but slow even though I use MKL

`private void TestImage2(Bitmap bitm, Model model)
        {
            using (var unknownImage = FaceRecognition.LoadImage(bitm))
            {
                var faceLocations = _FaceRecognition.FaceLocations(unknownImage, 0, model).ToArray();
                using (var g = Graphics.FromImage(bitm))
                    foreach (var l in faceLocations)
                        g.DrawRectangle(Pens.Yellow, l.Left, l.Top, l.Right - l.Left, l.Bottom - l.Top);
            }
            this.pictureBox1.Image = bitm;
        }`

**Comment by takuya-takeuchi** [comment]
@CodrTks 
How do you use MKL?
NcnnDotNet does not use MKL.
So your program could not use MKL even though you deploy intel mkl libs in apps or system dir.

**Comment by CodrTks** [comment]
@takuya-takeuchi 

I am using FaceRecognitionDotNet v4.0.30319. How can I get the face image as a bitmap in the code block above? I guess I need to speed it up a bit

**Comment by CodrTks** [comment]
In fact, I was comparing faces I detected using emgucv to FaceEncodings. It works fine, but emgucv face detection is very bad.

private Image FaceDtc(Bitmap bit)
        {
            Image imgs = null;
            Image<Bgr, byte> img = new Image<Bgr, byte>(bit);
            if (img != null)
            {
                Image<Gray, byte> grayframe = img.Convert<Gray, byte>();
                System.Drawing.Rectangle[] rectan = cassi.DetectMultiScale(grayframe, 1.1, 7, new System.Drawing.Size((grayframe.Size.Width / 10), (grayframe.Size.Height / 10)));
                foreach (var face in rectan)
                {
                    imgs = img.Copy(face).Convert<Rgb, byte>().Resize(221, 204, Emgu.CV.CvEnum.Inter.Area).ToBitmap();
                    //img.Draw("", new System.Drawing.Point(face.X + 2, face.Y - 10), FontFace.HersheyPlain, 2, new Bgr(Color.Yellow), 1, LineType.EightConnected, false);
                }
            }
            return imgs;
        }

**Comment by takuya-takeuchi** [comment]
> How can I get the face image as a bitmap in the code block above?

FRDN does not support to save cropped face as .NET Bitmap.

Face detection of FRDN is not fast.
You can refer this
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/4#issuecomment-421353167

It depends on dlib.

**Comment by CodrTks** [comment]
@takuya-takeuchi 
I understood thank you. Finally, do you have any suggestions for fast face detection and show snapshots in the picture box?

**Comment by takuya-takeuchi** [comment]
TBH, we should use other library to face detection.
dlib implementation may be accurate but it does not satisfy performance requirements.
We can try OpenVINO, tensorflow C++, torchlib and other support face detection models.

**Comment by CodrTks** [comment]
Thank you for patiently listening to me. I follow your work. I wish you happy days
