### ISSUE TITLE
The model binary file is not found.":null

### ISSUE THREAD

**Issue by dev-ptdi** [takuya-takeuchi/UltraFaceDotNet#6]
Hi,

I am facing with "The model binary file is not found.:null, when trying to run the example on Net Core 3.1,

I copy RFB-320.bin, RFB-320.param, test.jpg, UltraFaceDotNet.dll and NcnnDotNet.dll  in /bin folder

 var param = new UltraFaceParameter
            {
                BinFilePath = "RFB-320.bin RFB-320.param",
                ParamFilePath = "test.jpg",
                InputWidth = 320,
                InputLength = 240,
                NumThread = 1,
                ScoreThreshold = 0.7f
            };

            try
            {
                using (var ultraFace = UltraFace.Create(param)) // config model input
                {
                    var imageFile = param.ParamFilePath;

                    Console.WriteLine($"Processing {imageFile}");

                    using var frame = Cv2.ImRead(imageFile);
                    using var inMat = NcnnDotNet.Mat.FromPixels(frame.Data, NcnnDotNet.PixelType.Bgr2Rgb, frame.Cols, frame.Rows);

                    var faceInfos = ultraFace.Detect(inMat).ToArray();
                    for (var j = 0; j < faceInfos.Length; j++)
                    {
                        var face = faceInfos[j];
                        var pt1 = new Point<float>(face.X1, face.Y1);
                        var pt2 = new Point<float>(face.X2, face.Y2);
                        Cv2.Rectangle(frame, pt1, pt2, new Scalar<double>(0, 255, 0), 2);
                    }

                    Cv2.ImShow("UltraFace", frame);
                    Cv2.WaitKey();
                    Cv2.ImWrite("result.jpg", frame);
                

what I missed?

**Comment by takuya-takeuchi** [comment]
@dev-ptdi 

It could be

````
var param = new UltraFaceParameter
{
BinFilePath = "RFB-320.bin",
ParamFilePath = "RFB-320.param",
InputWidth = 320,
InputLength = 240,
NumThread = 1,
ScoreThreshold = 0.7f
};

and 


var imageFile = "test.jpg";
````

**Comment by dev-ptdi** [comment]
thanks.. how about to save the result to byte array?

**Comment by dev-ptdi** [comment]
thanks it works :)
