### ISSUE TITLE
Detect other object

### ISSUE THREAD

**Issue by dev-ptdi** [takuya-takeuchi/UltraFaceDotNet#8]
The results are OK,

I think I can use this to detect other object like car, cat, dog..

any idea or suggestion?

**Comment by takuya-takeuchi** [comment]
@dev-ptdi 
You should use OnnRuntime if you want to use Deep Learning.
This repo is porting of https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB.
